export const ADD_CAT = "ADD_CAT";
export const DELETE_CAT = "DELETE_CAT";
export const FETCH_CAT_REQUEST = "FETCH_CAT_REQUEST";
export const FETCH_CAT_SUCCESS = "FETCH_CAT_SUCCESS";
export const FETCH_CAT_FAILURE = "FETCH_CAT_FAILURE";
