export const ADD_LOTR = "ADD_LOTR";
export const DELETE_LOTR = "DELETE_LOTR";
export const FETCH_LOTR_REQUEST = "FETCH_LOTR_REQUEST";
export const FETCH_LOTR_SUCCESS = "FETCH_LOTR_SUCCESS";
export const FETCH_LOTR_FAILURE = "FETCH_LOTR_FAILURE";
